name: CosyVoice
on:
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/build.yml@main
    secrets: inherit
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      version: ${{ needs.build.outputs.version }}
      cluster: ai
